### ISSUE TITLE
使用 beforeShow或者 afterHide时添加事件

### ISSUE THREAD

**Issue by Hamer-2014** [hehaibao/hDialog#2]
在系统调用这两个函数中，无法使用 单击事件的 e.target获取源。好像您的data参数传递过来的是null。希望这块可以稍微做些改进。
我这边按照需要修改了如下代码，在元素的单击事件中传递了 e
T.on('click', function (e) { methods.open(_O, T, e); }

open: function (o, T, e) {
   ...
  this.fire.call(this, o.beforeShow, e);  //  原 this.fire.call(this, o.beforeShow);
  ...
}

close事件修改同上。希望能给您带来一些启发。
谢谢您的插件！

**Comment by hehaibao** [comment]
感谢您的反馈
